name: "Deploy to WordPress.org and create release on GitHub"

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag to run for'
  push:
    tags:
      - "v*"

# Prevent concurrent deployments
concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4
      # Optional: if we add a build step to the plugin, we can run it here.
        #- name: Build
        #  run: |
        #    composer install --no-dev --prefer-dist --optimize-autoloader --no-scripts
        #    yarn install
        #    grunt build
      # Deploy the plugin to WordPress.org
      - name: WordPress Plugin Deploy
        id: deploy
        uses: 10up/action-wordpress-plugin-deploy@develop
        with:
          generate-zip: true
        env:
          SLUG: curated-posts # optional, remove if GitHub repo name matches SVN slug, including capitalization
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
  build:
    name: Create Release
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
